"""
Training Pipeline for TinyMobileNet-XS on PIE Dataset
Includes: Data loading, training, validation, quantization, export for FPGA
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, Subset
from torch.amp import autocast, GradScaler
import pickle
import os
from pathlib import Path
import numpy as np
from tqdm import tqdm
from PIL import Image

from tinymobilenet_xs import (
    create_model, 
    fold_batch_norm,
    quantize_model_post_training,
    export_weights_to_int8
)


# ============================================================================
# 1. PIE DATASET CLASS
# ============================================================================

class PIEIntentionDataset(Dataset):
    """
    PyTorch Dataset for PIE Pedestrian Intention Estimation
    
    Loads from .pkl files generated by generate_pie_database.py
    """
    
    def __init__(self, pkl_file, pie_root_path, max_frames=4, transform=None, split='train'):
        """
        Args:
            pkl_file: Path to train_sequences.pkl or test_sequences.pkl
            pie_root_path: Root path to PIE dataset
            max_frames: Maximum frames per sequence (clips longer sequences)
            transform: torchvision transforms
            split: 'train' or 'test'
        """
        self.pkl_file = pkl_file
        self.pie_root = pie_root_path
        self.max_frames = max_frames
        self.transform = transform
        self.split = split
        
        # Load pickle file
        with open(pkl_file, 'rb') as f:
            data = pickle.load(f)
        
        self.image_sequences = data['image']  # List of frame path sequences
        self.labels = data['intention_binary']  # List of labels
        
        # Statistics tracking
        self.real_images_loaded = 0
        self.black_frames_used = 0
        self.total_frames_processed = 0
        self.failed_paths = []
        
        print(f"Loaded {len(self.image_sequences)} samples from {split} set")
        
        # Print class distribution
        labels_flat = [int(x[0][0]) for x in self.labels]
        crossing = sum(labels_flat)
        not_crossing = len(labels_flat) - crossing
        print(f"  Class distribution: {not_crossing} not-crossing, {crossing} crossing")
        
        print(f"\n⏳ [Dataset] Starting to load images...")
        print(f"   This will take a moment to scan all paths...\n")
    
    def __len__(self):
        return len(self.image_sequences)
    
    def __getitem__(self, idx):
        """
        Returns:
            frames: (T, 3, 64, 64) - temporal sequence of RGB frames
            label: int - binary label (0=not crossing, 1=crossing)
        """
        image_paths = self.image_sequences[idx]
        label = int(self.labels[idx][0][0])  # Extract label from nested list
        
        # Limit to max_frames
        image_paths = image_paths[:self.max_frames]
        num_frames = len(image_paths)
        
        # Load frames
        frames = []
        
        for path in image_paths:
            img_loaded = False
            try:
                # First try original path
                if os.path.exists(path):
                    img_path = path
                    img_loaded = True
                else:
                    # Path doesn't exist, try to reconstruct it correctly
                    path_obj = Path(path)
                    parts = path_obj.parts
                    
                    # Extract filename and folder names
                    filename = path_obj.name  # e.g., "04511.png"
                    
                    # Find set (set01, set02, etc) and video folder
                    set_name = None
                    video_name = None
                    
                    for part in parts:
                        if part.startswith('set') and len(part) == 5 and part[3:].isdigit():
                            set_name = part
                        if part.startswith('video') and '_' in part:
                            video_name = part
                    
                    # Reconstruct correct path
                    if set_name and video_name:
                        img_path = os.path.join(self.pie_root, 'images', set_name, video_name, filename)
                        
                        if not os.path.exists(img_path):
                            # Try without underscore in video name
                            video_name_alt = video_name.replace('_', '')
                            img_path = os.path.join(self.pie_root, 'images', set_name, video_name_alt, filename)
                            
                            if not os.path.exists(img_path):
                                # Last resort: search in all subdirectories
                                found = False
                                for root, dirs, files in os.walk(os.path.join(self.pie_root, 'images')):
                                    if filename in files:
                                        img_path = os.path.join(root, filename)
                                        found = True
                                        img_loaded = True
                                        break
                                
                                if not found:
                                    # ❌ IMAGE NOT FOUND
                                    self.total_frames_processed += 1
                                    self.black_frames_used += 1
                                    if path not in self.failed_paths:
                                        self.failed_paths.append(path)
                                        print(f"❌ [FAILED] Image not found: {filename}")
                                    frames.append(np.zeros((64, 64, 3), dtype=np.float32))
                                    continue
                            else:
                                img_loaded = True
                        else:
                            img_loaded = True
                    else:
                        # ❌ CANNOT RECONSTRUCT PATH
                        self.total_frames_processed += 1
                        self.black_frames_used += 1
                        if path not in self.failed_paths:
                            self.failed_paths.append(path)
                            print(f"❌ [FAILED] Cannot parse path: {path}")
                        frames.append(np.zeros((64, 64, 3), dtype=np.float32))
                        continue
                
                # Load image from reconstructed/original path
                if img_loaded:
                    img = Image.open(img_path).convert('RGB')
                    
                    # Resize to 64×64 if needed
                    if img.size != (64, 64):
                        img = img.resize((64, 64), Image.BILINEAR)
                    
                    # Convert to numpy array
                    img_array = np.array(img, dtype=np.float32) / 255.0  # Normalize to [0, 1]
                    
                    # Check if image is mostly black (loading issue)
                    mean_val = np.mean(img_array)
                    if mean_val < 0.05:
                        print(f"⚠️  [BLACK IMAGE] {Path(img_path).name} (mean={mean_val:.3f}) - Might be empty!")
                        self.black_frames_used += 1
                    else:
                        self.real_images_loaded += 1
                    
                    # Apply transform if any
                    if self.transform:
                        img_array = self.transform(img_array)
                    
                    frames.append(img_array)
                    self.total_frames_processed += 1
            
            except Exception as e:
                # ❌ ERROR LOADING IMAGE
                self.total_frames_processed += 1
                self.black_frames_used += 1
                if path not in self.failed_paths:
                    self.failed_paths.append(path)
                    print(f"❌ [ERROR] Could not load {Path(path).name}: {str(e)[:50]}")
                frames.append(np.zeros((64, 64, 3), dtype=np.float32))
        
        # Convert to torch tensor
        frames = np.stack(frames, axis=0)  # (T, 64, 64, 3)
        frames = torch.from_numpy(frames).permute(0, 3, 1, 2)  # (T, 3, 64, 64)
        
        # Pad to max_frames if needed
        if num_frames < self.max_frames:
            padding = torch.zeros(self.max_frames - num_frames, 3, 64, 64)
            frames = torch.cat([frames, padding], dim=0)
        
        # Print statistics every 100 samples
        if (idx + 1) % 100 == 0:
            real_pct = 100 * self.real_images_loaded / max(1, self.total_frames_processed)
            black_pct = 100 * self.black_frames_used / max(1, self.total_frames_processed)
            print(f"📊 [Progress] Processed {idx+1}/{len(self)} samples")
            print(f"   ✅ Real images: {self.real_images_loaded} ({real_pct:.1f}%)")
            print(f"   ⚫ Black frames: {self.black_frames_used} ({black_pct:.1f}%)")
            print(f"   ❌ Failed paths: {len(self.failed_paths)}")
        
        return frames, torch.tensor(label, dtype=torch.long)


# ============================================================================
# 2. TRAINING UTILITIES
# ============================================================================

class AverageMeter:
    """Track average metric values"""
    def __init__(self):
        self.reset()
    
    def reset(self):
        self.val = 0
        self.avg = 0
        self.sum = 0
        self.count = 0
    
    def update(self, val, n=1):
        self.val = val
        self.sum += val * n
        self.count += n
        self.avg = self.sum / self.count


def accuracy(output, target, topk=(1,)):
    """Compute accuracy"""
    with torch.no_grad():
        maxk = max(topk)
        batch_size = target.size(0)
        
        _, pred = output.topk(maxk, 1, True, True)
        pred = pred.t()
        correct = pred.eq(target.view(1, -1).expand_as(pred))
        
        res = []
        for k in topk:
            correct_k = correct[:k].reshape(-1).float().sum(0, keepdim=True)
            res.append(correct_k.mul_(100.0 / batch_size))
        return res


def macro_f1_binary(y_true, y_pred):
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    f1_scores = []
    for cls in [0, 1]:
        tp = np.sum((y_true == cls) & (y_pred == cls))
        fp = np.sum((y_true != cls) & (y_pred == cls))
        fn = np.sum((y_true == cls) & (y_pred != cls))
        precision = tp / max(1, tp + fp)
        recall = tp / max(1, tp + fn)
        if precision + recall == 0:
            f1 = 0.0
        else:
            f1 = 2.0 * precision * recall / (precision + recall)
        f1_scores.append(f1)
    return float(sum(f1_scores) / len(f1_scores))


# ============================================================================
# 3. TRAINING LOOP
# ============================================================================

def train_epoch(model, train_loader, criterion, optimizer, device, epoch, scaler=None):
    """Train for one epoch with optional mixed precision"""
    model.train()
    
    losses = AverageMeter()
    top1_acc = AverageMeter()
    
    pbar = tqdm(train_loader, desc=f'Epoch {epoch} [TRAIN]')
    
    # Determine device type for autocast
    device_type = 'cuda' if 'cuda' in str(device) else 'cpu'
    
    for frames, labels in pbar:
        frames = frames.to(device)
        labels = labels.to(device)
        
        optimizer.zero_grad()
        
        # Mixed precision training (if scaler provided)
        if scaler is not None:
            with autocast(device_type=device_type):
                logits = model(frames)
                loss = criterion(logits, labels)
            
            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            scaler.step(optimizer)
            scaler.update()
        else:
            # Standard training (without mixed precision)
            logits = model(frames)
            loss = criterion(logits, labels)
            loss.backward()
            optimizer.step()
        
        # Track metrics
        acc = accuracy(logits, labels)[0][0].item()
        losses.update(loss.item(), frames.size(0))
        top1_acc.update(acc, frames.size(0))
        
        pbar.set_postfix({'loss': f'{losses.avg:.4f}', 'acc': f'{top1_acc.avg:.2f}%'})
    
    return losses.avg, top1_acc.avg


def validate(model, val_loader, criterion, device, epoch):
    """Validate model"""
    model.eval()

    losses = AverageMeter()
    top1_acc = AverageMeter()
    all_preds = []
    all_labels = []

    pbar = tqdm(val_loader, desc=f'Epoch {epoch} [VAL]')

    device_type = 'cuda' if 'cuda' in str(device) else 'cpu'

    with torch.no_grad():
        for frames, labels in pbar:
            frames = frames.to(device)
            labels = labels.to(device)

            with autocast(device_type=device_type):
                logits = model(frames)
                loss = criterion(logits, labels)

            preds = torch.argmax(logits, dim=1)
            acc = accuracy(logits, labels)[0][0].item()
            losses.update(loss.item(), frames.size(0))
            top1_acc.update(acc, frames.size(0))
            all_preds.extend(preds.cpu().numpy().tolist())
            all_labels.extend(labels.cpu().numpy().tolist())

            pbar.set_postfix({'loss': f'{losses.avg:.4f}', 'acc': f'{top1_acc.avg:.2f}%'})

    val_macro_f1 = macro_f1_binary(all_labels, all_preds)
    return losses.avg, top1_acc.avg, val_macro_f1


def stratified_split_indices(labels, val_ratio=0.2, seed=42):
    labels = np.array(labels)
    rng = np.random.default_rng(seed)
    train_idx = []
    val_idx = []
    for cls in np.unique(labels):
        cls_idx = np.where(labels == cls)[0]
        rng.shuffle(cls_idx)
        n_val = max(1, int(round(len(cls_idx) * val_ratio)))
        val_idx.extend(cls_idx[:n_val].tolist())
        train_idx.extend(cls_idx[n_val:].tolist())
    rng.shuffle(train_idx)
    rng.shuffle(val_idx)
    return train_idx, val_idx


def train_model(
    model,
    train_loader,
    val_loader,
    num_epochs=30,
    learning_rate=1e-3,
    weight_decay=1e-4,
    device='cuda',
    checkpoint_dir='./checkpoints',
    use_mixed_precision=True,
    class_counts=None
):
    """Full training pipeline with optional mixed precision"""

    os.makedirs(checkpoint_dir, exist_ok=True)
    checkpoint_path = os.path.join(checkpoint_dir, 'best_model.pth')

    if class_counts is None:
        class_counts = [1, 1]
    total = float(sum(class_counts))
    class_weights = torch.tensor([
        total / max(1.0, 2.0 * float(class_counts[0])),
        total / max(1.0, 2.0 * float(class_counts[1]))
    ], dtype=torch.float32).to(device)
    print(f"\n[CLASS WEIGHTS] Dynamic weights from training labels:")
    print(f"  Class 0 count = {class_counts[0]}, weight = {class_weights[0]:.4f}")
    print(f"  Class 1 count = {class_counts[1]}, weight = {class_weights[1]:.4f}")

    criterion = nn.CrossEntropyLoss(weight=class_weights)
    optimizer = optim.Adam(model.parameters(), lr=learning_rate, weight_decay=weight_decay)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=num_epochs)

    scaler = GradScaler() if use_mixed_precision and device == 'cuda' else None
    if scaler:
        print("Using mixed precision training (FP16) for 1.5-2x speedup!")

    best_acc = 0.0
    best_f1 = -1.0
    best_epoch = 0
    start_epoch = 0

    if os.path.exists(checkpoint_path):
        try:
            ckpt = torch.load(checkpoint_path, map_location=device)
            if 'model_state_dict' in ckpt:
                model.load_state_dict(ckpt['model_state_dict'])
            if 'optimizer_state_dict' in ckpt:
                optimizer.load_state_dict(ckpt['optimizer_state_dict'])
            best_acc = float(ckpt.get('best_acc', 0.0))
            best_f1 = float(ckpt.get('best_f1', -1.0))
            best_epoch = int(ckpt.get('epoch', 0))
            start_epoch = best_epoch + 1
            print(f"[RESUME] Loaded checkpoint from {checkpoint_path}")
            print(f"         Resume from epoch {start_epoch} | best_acc={best_acc:.2f}% best_f1={best_f1:.4f}")
        except Exception as e:
            print(f"[WARN] Could not resume from checkpoint: {e}")
            # If resume fails, just train from scratch
            start_epoch = 0

    print("=" * 80)
    print("Starting training (best checkpoint selected by validation accuracy)...")
    print("=" * 80)

    for epoch in range(start_epoch, num_epochs):
        train_loss, train_acc = train_epoch(model, train_loader, criterion, optimizer, device, epoch, scaler)
        val_loss, val_acc, val_f1 = validate(model, val_loader, criterion, device, epoch)
        scheduler.step()

        print(f"\nEpoch {epoch:3d}: "
              f"train_loss={train_loss:.4f} train_acc={train_acc:.2f}% | "
              f"val_loss={val_loss:.4f} val_acc={val_acc:.2f}% val_f1={val_f1:.4f}")

        if val_acc > best_acc or (val_acc == best_acc and val_f1 > best_f1):
            best_acc = val_acc
            best_f1 = val_f1
            best_epoch = epoch
            checkpoint_path = os.path.join(checkpoint_dir, 'best_model.pth')
            torch.save({
                'epoch': epoch,
                'model_state_dict': model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'best_acc': best_acc,
                'best_f1': best_f1
            }, checkpoint_path)
            print(f"✓ Saved best model (acc={best_acc:.2f}%, f1={best_f1:.4f}) to {checkpoint_path}")

    print("\n" + "=" * 80)
    print(f"Training complete! Best accuracy: {best_acc:.2f}% | Best macro-F1: {best_f1:.4f} at epoch {best_epoch}")
    print("=" * 80)

    return model


# ============================================================================
# 4. QUANTIZATION & EXPORT PIPELINE
# ============================================================================

def quantize_and_export(model, calibration_loader, device, output_dir='./fpga_weights'):
    """
    Full quantization and export pipeline
    
    1. Fold BatchNorm into Conv weights
    2. Quantize using post-training quantization
    3. Export to INT8 C header for FPGA
    """
    os.makedirs(output_dir, exist_ok=True)
    
    print("\n" + "=" * 80)
    print("Quantization & Export Pipeline")
    print("=" * 80)
    
    # Step 1: Fold BatchNorm
    print("\n[1/3] Folding BatchNorm...")
    model_fused = fold_batch_norm(model)
    
    # Step 2: Quantize
    print("[2/3] Quantizing model (Post-Training Quantization)...")
    model_int8, quant_config = quantize_model_post_training(
        model_fused, 
        calibration_loader,
        device=device
    )
    
    # Step 3: Export
    print("[3/3] Exporting INT8 weights...")
    output_file = os.path.join(output_dir, 'tinymobilenet_xs_weights.h')
    export_weights_to_int8(model_int8, quant_config, output_file=output_file)
    
    # Save quantization config
    import json
    config_file = os.path.join(output_dir, 'quantization_config.json')
    with open(config_file, 'w') as f:
        json.dump({
            'weight_scales': quant_config.weight_scales,
            'activation_scales': quant_config.activation_scales
        }, f, indent=2)
    
    print(f"✓ Exported to {output_dir}/")
    print(f"  - Weights: tinymobilenet_xs_weights.h")
    print(f"  - Config: quantization_config.json")
    
    return model_int8, quant_config


# ============================================================================
# 5. MAIN TRAINING SCRIPT
# ============================================================================

def main():
    """Main training entry point"""

    REPO_ROOT = Path(__file__).resolve().parent
    PIE_ROOT = str(REPO_ROOT)
    TRAIN_PKL = str(REPO_ROOT / 'data_cache' / 'sequences' / 'train_sequences.pkl')
    TEST_PKL = str(REPO_ROOT / 'data_cache' / 'sequences' / 'test_sequences.pkl')

    BATCH_SIZE = 16
    NUM_EPOCHS = 50
    LEARNING_RATE = 1e-3
    WEIGHT_DECAY = 5e-4
    NUM_WORKERS = 0
    MAX_FRAMES = 4
    USE_MIXED_PRECISION = False
    DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

    print("=" * 80)
    print("TinyMobileNet-XS Training")
    print("=" * 80)
    print(f"Device: {DEVICE}")
    print(f"Batch size: {BATCH_SIZE}")
    print(f"Epochs: {NUM_EPOCHS}")
    print(f"Learning rate: {LEARNING_RATE}")
    print(f"Weight decay: {WEIGHT_DECAY}")
    print(f"Mixed precision: {USE_MIXED_PRECISION}")
    print(f"Max frames per sequence: {MAX_FRAMES}")
    print()
    print("✅ Using internal stratified 80/20 split from train_sequences.pkl")
    print("✅ External set05 kept only for final evaluation / export")
    print("=" * 80)

    print("\nLoading base training dataset...")
    full_dataset = PIEIntentionDataset(
        TRAIN_PKL,
        PIE_ROOT,
        max_frames=MAX_FRAMES,
        split='train_full'
    )
    external_test_dataset = PIEIntentionDataset(
        TEST_PKL,
        PIE_ROOT,
        max_frames=MAX_FRAMES,
        split='test_external'
    )

    full_labels = [int(x[0][0]) for x in full_dataset.labels]
    train_indices, val_indices = stratified_split_indices(full_labels, val_ratio=0.2, seed=42)
    train_dataset = Subset(full_dataset, train_indices)
    val_dataset = Subset(full_dataset, val_indices)

    train_labels = [full_labels[i] for i in train_indices]
    val_labels = [full_labels[i] for i in val_indices]
    class_0_count = sum(lbl == 0 for lbl in train_labels)
    class_1_count = sum(lbl == 1 for lbl in train_labels)

    print(f"\nSplit summary:")
    print(f"  Train samples: {len(train_indices)} | class0={sum(l == 0 for l in train_labels)} class1={sum(l == 1 for l in train_labels)}")
    print(f"  Val samples:   {len(val_indices)} | class0={sum(l == 0 for l in val_labels)} class1={sum(l == 1 for l in val_labels)}")
    print(f"  External test samples: {len(external_test_dataset)}")

    train_loader = DataLoader(
        train_dataset,
        batch_size=BATCH_SIZE,
        shuffle=True,
        num_workers=NUM_WORKERS,
        pin_memory=True
    )
    val_loader = DataLoader(
        val_dataset,
        batch_size=BATCH_SIZE,
        shuffle=False,
        num_workers=NUM_WORKERS,
        pin_memory=True
    )
    test_loader = DataLoader(
        external_test_dataset,
        batch_size=BATCH_SIZE,
        shuffle=False,
        num_workers=NUM_WORKERS,
        pin_memory=True
    )

    print("\nCreating model...")
    model = create_model(num_classes=2, t_frames=MAX_FRAMES)
    model = model.to(DEVICE)

    model = train_model(
        model,
        train_loader,
        val_loader,
        num_epochs=NUM_EPOCHS,
        learning_rate=LEARNING_RATE,
        weight_decay=WEIGHT_DECAY,
        device=DEVICE,
        use_mixed_precision=USE_MIXED_PRECISION,
        class_counts=[class_0_count, class_1_count]
    )

    print("\nQuantizing and exporting for FPGA...")
    quantize_and_export(
        model,
        test_loader,
        device=DEVICE,
        output_dir='./fpga_weights'
    )

    print("\n" + "=" * 80)
    print("✓ Training complete!")
    print(f"✓ Best model: checkpoints/best_model.pth")
    print(f"✓ FPGA weights: fpga_weights/tinymobilenet_xs_weights.h")
    print(f"✓ Use in RTL: copy tinymobilenet_xs_weights.h to Vivado project")
    print("=" * 80)


if __name__ == '__main__':
    main()
